=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/product.schema.json",
  "title": "CulturesIniParameterInformation",
  "description": "The definition of a parameter in the map.ini in Cultures.",
  "type": "object",
  "properties": {
    "name": {
      "description": "Name of the command",
      "type": "string"
    },
    "category": {
      "description": "The category enum the command belongs to.",
      "type": "string"
    },
    "displayName": {
      "description": "A more readable name to display (camel case)",
      "type": "string"
    },
    "documentation": {
      "description": "Documentation about the usage of the command (markdown).",
      "type": "string"
    },
    "parametersMin": {
      "type": "number",
      "description": "Minimum count of parameters."
    },
    "parametersMax": {
      "type": "number",
      "description": "Maximum count of parameters."
    },
    "parameters": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "documentation": {
              "type": "string",
              "description": "(markdown)"
            },
            "type": {
              "type": "string",
              "enum": [
                "NUMBER",
                "TYPE"
              ]
            }
          },
          "anyOf": [
            {
              "properties": {
                "type": {
                  "const": "NUMBER"
                },
                "numberRange": {
                  "type": "object",
                  "properties": {
                    "min": {
                      "type": "integer"
                    },
                    "max": {
                      "type": "integer"
                    }
                  },
                  "additionalProperties": false
                },
                "numberHint": {
                  "type": "array",
                  "description": "Assigns names to the numbers this parameter takes. Used for automatic documentation to show the user-friendly name for numbers. Array is zero-based. Special value `<NONE>` is hidden from the user.",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                },
                "numberHintsBitfield": {
                  "type": "array",
                  "description": "Like number hint, but assigns a user-friendly name to every bit of the number taken by this parameter. Array starts with the lowest-value bit.",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                }
              },
              "required": [
                "type"
              ],
              "additionalProperties": false
            },
            {
              "properties": {
                "type": {
                  "const": "TYPE"
                }
              }
            }
          ],
          "required": [
            "name",
            "type"
          ],
          "additionalProperties": false
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "name",
    "category",
    "parameters"
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/player.json
{
  "name": "Player",
  "category": "playerdata",
  "documentation": "Defines a player.",
  "parameters": [
    {
      "name": "PlayerId",
      "documentation": "The id of the player to be created.",
      "type": "NUMBER",
      "numberRange": {
        "min": 0,
        "max": 19
      }
    },
    {
      "name": "PlayerType",
      "documentation": "The type of the player.\n\n*Note*: Must be `human` if the player integrated to human player in running game.",
      "type": "NUMBER",
      "numberRange": {
        "min": 1,
        "max": 2
      },
      "numberHints": [
        "<HIDE>",
        "HUMAN",
        "AI"
      ]
    },
    {
      "name": "TribeType",
      "documentation": "The tribe of the player.",
      "type": "NUMBER",
      "numberRange": {
        "min": 1,
        "max": 41
      },
      "numberHints": [
        "<HIDE>",
        "VIKING",
        "FRANK",
        "BYZANTINE",
        "SARACEN",
        "WERESNAKE",
        "WEREWOLF",
        "EGYPT",
        "BEARS",
        "BOARS",
        "CATTLE",
        "DEERSMALE",
        "DEERSFEMALE",
        "DOGS",
        "GOATSTAME",
        "GOATSWILD",
        "RABBITSBROWN",
        "RABBITSWHITE",
        "RABBITSEVIL",
        "SHEEP",
        "WOLVES",
        "CAMELS",
        "DROMEDARIES",
        "ELEPHANTS",
        "HORSES",
        "LIONSMALE",
        "LIONSFEMALE",
        "BIRDSSPARROWS",
        "BIRDSRAVENS",
        "BIRDSPARROTS",
        "CHICKEN",
        "DUCKS",
        "GEESE",
        "SWANS",
        "BEES",
        "BUTTERFLIES",
        "MOSQUITOS",
        "CRABS",
        "FROGS",
        "SCORPIONS",
        "SNAKES",
        "DRAGONS"
      ]
    },
    {
      "name": "ColorId",
      "documentation": "The color of the player.",
      "type": "NUMBER",
      "range": {
        "min": 1,
        "max": 2
      },
      "numberHints": [
        "BLUE",
        "RED",
        "YELLOW",
        "CYAN",
        "GREEN",
        "PURPLE",
        "GREY",
        "ORANGE",
        "NEON",
        "BLACK"
      ]
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/results/infocountanimalsinarea.json
{
  "name": "InfoCountAnimalsInArea",
  "category": "<dummy>",
  "documentation": "Shows the number of animals in the given area in the top right of the screen for the given player.\n\n*Note*: Only works with sheep and cattle.",
  "parameters": [
    {
      "name": "PlayerId",
      "type": "NUMBER"
    },
    {
      "name": "LineId",
      "type": "NUMBER"
    },
    {
      "name": "StringId",
      "documentation": "Place '%d' where the counted number should appear and another where the comparison number should appear.",
      "type": "NUMBER"
    },
    {
      "name": "TribeType",
      "documentation": "Only cattle and sheep work.",
      "type": "TYPE"
    },
    {
      "name": "PosX",
      "type": "NUMBER"
    },
    {
      "name": "PosY",
      "type": "NUMBER"
    },
    {
      "name": "Radius",
      "type": "NUMBER"
    },
    {
      "name": "Comparison",
      "documentation": "Allows to add a target (like '10/15 sheep') in the command rather than in the string.",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/goals/randomtimegone.json
{
  "name": "RandomTimeGone",
  "category": "<dummy>",
  "documentation": "Satisfied if a random amount of seconds elapsed. The given time is used as the maximum and the minimum is half the maximum.",
  "parameters": [
    {
      "name": "MaximumNumberOfSeconds",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/ai_setcondition_ontimer.json
{
  "name": "AI_SetCondition_OnTimer",
  "category": "aidata",
  "documentation": "Sets the given condition of the given player after the give amount of minutes to true (=10000).",
  "parameters": [
    {
      "name": "PlayerId",
      "type": "NUMBER"
    },
    {
      "name": "ConditionId",
      "type": "NUMBER"
    },
    {
      "name": "TimeInitial",
      "documentation": "Time before the TimeTrueCycle (with the other duration) starts. Condition is `false`. Given in twelves of a second (=> 120 is 10 seconds). Rounded to 10 seconds.",
      "type": "NUMBER"
    },
    {
      "name": "TimeTrueCycle",
      "documentation": "Time frame where the condition stays on `true`. Given in 640th of a minute (6400 => 10 minutes). Rounded to 10 seconds. Switches to the TimeFalseCycle when out of time.",
      "type": "NUMBER"
    },
    {
      "name": "TimeFalseCycle",
      "documentation": "Time frame where the condition stays on `false`. Given in 640s of a minute (6400 => 10 minutes). Rounded to 10 seconds. Switches to the TimeTrueCycle when out of time.",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/results/changemissionidofhumaninrange.json
{
  "name": "ChangeMissionIdOfHumanInRange",
  "category": "<dummy>",
  "documentation": "TODO Difference to `ChangeHumanObjectIdInArea`?",
  "parameters": [
    {
      "name": "PlayerId",
      "type": "NUMBER"
    },
    {
      "name": "HumanId",
      "type": "NUMBER"
    },
    {
      "name": "PosX",
      "type": "NUMBER"
    },
    {
      "name": "PosY",
      "type": "NUMBER"
    },
    {
      "name": "Radius",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/goals/buildhouses.json
{
  "name": "BuildHouses",
  "category": "<dummy>",
  "documentation": "Satisfied as long as NOT enough houses of the given type of the given player with given quantity have been built.\n\n*Note*: Effectively an inverted version of \"player has 'n' houses of type\".",
  "parameters": [
    {
      "name": "PlayerId",
      "type": "NUMBER"
    },
    {
      "name": "HouseType",
      "type": "TYPE"
    },
    {
      "name": "Quantity",
      "type": "NUMBER"
    },
    {
      "name": "ObjectId",
      "documentation": "This id is assigned to the house(es). Probably, when this condition stops being fulfilled.",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/results/missionquitandplayvideo.json
{
  "name": "Mission quit and play video",
  "category": "<dummy>",
  "documentation": "Quits the current mission/map and plays the given video.",
  "parameters": [
    {
      "name": "VideoId",
      "documentation": "Number will be resolved to '$gameroot$/dataX/FMV/(Ger/Eng,...)/seq_XXXX.mpg'",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/setguide.json
{
  "name": "SetGuide",
  "category": "StaticObjects",
  "documentation": "Sets a guide into the world on the given position.",
  "parameters": [
    {
      "name": "PlayerId",
      "documentation": "The player the guide belongs to.",
      "type": "NUMBER"
    },
    {
      "name": "PosX",
      "type": "NUMBER"
    },
    {
      "name": "PosY",
      "type": "NUMBER"
    }
  ]
}
