=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/product.schema.json",
  "title": "CulturesIniParameterInformation",
  "description": "The definition of a parameter in the map.ini in Cultures.",
  "type": "object",
  "properties": {
    "name": {
      "description": "Name of the command",
      "type": "string"
    },
    "category": {
      "description": "The category enum the command belongs to.",
      "type": "string"
    },
    "displayName": {
      "description": "A more readable name to display (camel case)",
      "type": "string"
    },
    "documentation": {
      "description": "Documentation about the usage of the command (markdown).",
      "type": "string"
    },
    "parametersMin": {
      "type": "number",
      "description": "Minimum count of parameters."
    },
    "parametersMax": {
      "type": "number",
      "description": "Maximum count of parameters."
    },
    "parameters": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "documentation": {
              "type": "string",
              "description": "(markdown)"
            },
            "type": {
              "type": "string",
              "enum": [
                "NUMBER",
                "TYPE"
              ]
            }
          },
          "anyOf": [
            {
              "properties": {
                "type": {
                  "const": "NUMBER"
                },
                "numberRange": {
                  "type": "object",
                  "properties": {
                    "min": {
                      "type": "integer"
                    },
                    "max": {
                      "type": "integer"
                    }
                  },
                  "additionalProperties": false
                },
                "numberHint": {
                  "type": "array",
                  "description": "Assigns names to the numbers this parameter takes. Used for automatic documentation to show the user-friendly name for numbers. Array is zero-based. Special value `<NONE>` is hidden from the user.",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                },
                "numberHintsBitfield": {
                  "type": "array",
                  "description": "Like number hint, but assigns a user-friendly name to every bit of the number taken by this parameter. Array starts with the lowest-value bit.",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                }
              },
              "required": [
                "type"
              ],
              "additionalProperties": false
            },
            {
              "properties": {
                "type": {
                  "const": "TYPE"
                }
              }
            }
          ],
          "required": [
            "name",
            "type"
          ],
          "additionalProperties": false
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "name",
    "category",
    "parameters"
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/musictype.json
{
  "name": "MusicType",
  "category": "misc_music",
  "documentation": "Specifies the background music track.",
  "parameters": [
    {
      "name": "MusicType",
      "type": "NUMBER",
      "numberRange": {
        "min": 0,
        "max": 38
      },
      "numberHints": [
        "#DM_MUSIC_TYPE_NOMUSIC",
        "#DM_MUSIC_TYPE_CULTURE_MISSION",
        "#DM_MUSIC_TYPE_CULTURE_VIKING",
        "#DM_MUSIC_TYPE_CULTURE_FRANKEN",
        "#DM_MUSIC_TYPE_CULTURE_BYZANZ",
        "#DM_MUSIC_TYPE_CULTURE_ARABS",
        "#DM_MUSIC_TYPE_ATTACK_VIKING",
        "#DM_MUSIC_TYPE_ATTACK_FRANKEN",
        "#DM_MUSIC_TYPE_ATTACK_BYZANZ",
        "#DM_MUSIC_TYPE_ATTACK_ARABS",
        "#DM_MUSIC_TYPE_MISSION_VIKING1",
        "#DM_MUSIC_TYPE_MISSION_FRANKEN1",
        "#DM_MUSIC_TYPE_MISSION_FRANKEN2",
        "#DM_MUSIC_TYPE_MISSION_BYZANZ1",
        "#DM_MUSIC_TYPE_MISSION_BYZANZ2",
        "#DM_MUSIC_TYPE_MISSION_BYZANZ3",
        "#DM_MUSIC_TYPE_MISSION_BYZANZ4",
        "#DM_MUSIC_TYPE_MISSION_ARABS1",
        "#DM_MUSIC_TYPE_MISSION_ARABS2",
        "#DM_MUSIC_TYPE_MISSION_ARABS3",
        "#DM_MUSIC_TYPE_MISSION_MIDGARD1",
        "#DM_MUSIC_TYPE_MISSION_MIDGARD2",
        "#DM_MUSIC_TYPE_JINGLE_MARRIAGE",
        "#DM_MUSIC_TYPE_JINGLE_BIRTH",
        "#DM_MUSIC_TYPE_JINGLE_CIVILDEFENSE",
        "#DM_MUSIC_TYPE_JINGLE_DEATH",
        "#DM_MUSIC_TYPE_JINGLE_HOUSEBUILT",
        "#DM_MUSIC_TYPE_JINGLE_WON",
        "#DM_MUSIC_TYPE_JINGLE_LOST",
        "#DM_MUSIC_TYPE_JINGLE_TECHNOLOGY",
        "#DM_MUSIC_TYPE_JINGLE_OPENCHEST",
        "#DM_MUSIC_TYPE_ADDON_MISSION_ARABS1",
        "#DM_MUSIC_TYPE_ADDON_MISSION_ARABS2",
        "#DM_MUSIC_TYPE_ADDON_MISSION_FRANKEN1",
        "#DM_MUSIC_TYPE_ADDON_MISSION_FRANKEN2",
        "#DM_MUSIC_TYPE_ADDON_MISSION_FRANKEN3",
        "#DM_MUSIC_TYPE_ADDON_MISSION_NORDLAND",
        "#DM_MUSIC_TYPE_ADDON_MISSION_UNDERWORLD",
        "#DM_MUSIC_TYPE_ADDON_MISSION_ASGARD"
      ]
    },
    {
      "name": "HouseType",
      "documentation": "E.g. 1 (#HOUSE_TYPE_HEADQUARTERS)",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/goals/goodsinhouses.json
{
  "name": "GoodsInHouses",
  "category": "<dummy>",
  "documentation": "Satisfied if equal to or more than the given amount of the given good is stored in the given warehouse.",
  "parameters": [
    {
      "name": "ObjectId",
      "documentation": "The id of the warehouse.",
      "type": "NUMBER"
    },
    {
      "name": "GoodType",
      "type": "TYPE"
    },
    {
      "name": "Amount",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/relationnotchangeable.json
{
  "name": "RelationNotChangeable",
  "category": "playermisc",
  "documentation": "Makes PlayerA unable to change the diplomatic relation to PlayerB.\n\n*Note*: Can be modified by mission command `SetDiplomacyNotChangeableFlag`.",
  "parameters": [
    {
      "name": "PlayerIdA",
      "type": "NUMBER"
    },
    {
      "name": "PlayerIdB",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/playerfixcolors.json
{
  "name": "PlayerFixColors",
  "category": "multiplayer",
  "documentation": "Defines if colors are un-changeable in the multiplayer lobby.",
  "parameters": [
    {
      "name": "IsFixed",
      "documentation": "`0` if colors should be changeable; `1` otherwise.",
      "type": "NUMBER",
      "numberRange": {
        "min": 0,
        "max": 1
      }
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/maptype.json
{
  "name": "MapType",
  "category": "misc_maptype",
  "documentation": "Controls where or if the map is displayed in the menu.\n\n*See*: [German documentation](https://www.wikinger-tommy.de/download/intern/Misc.pdf)",
  "parameters": [
    {
      "name": "MapTypeId",
      "type": "NUMBER",
      "numberRange": {
        "min": 1,
        "max": 6
      },
      "numberHint": [
        "#CLEAN_MAP_TYPE_SINGLE_PLAYER_CAMPAIGN: For submissions; Needs the `mapcampaignid` command",
        "#CLEAN_MAP_TYPE_SINGLE_PLAYER_FREE: Normal singleplayer map",
        "#CLEAN_MAP_TYPE_SINGLE_PLAYER_DEMO: Unknown",
        "#CLEAN_MAP_TYPE_MULTI_PLAYER_FREE: Normal multiplayer map",
        "#CLEAN_MAP_TYPE_USER_SINGLE_PLAYER_FREE: Maps created with external editor",
        "#CLEAN_MAP_TYPE_USER_MULTI_PLAYER_FREE: Maps created with external editor"
      ]
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/successfullif.json
{
  "name": "SuccessfullIf",
  "category": "MissionData",
  "documentation": "States the number of conditions (or logical requirements) that need to be true such that the mission is activated.",
  "parameters": [
    {
      "name": "LetterType",
      "type": "NUMBER",
      "numberRange": {
        "min": 0,
        "max": 3
      },
      "numberHints": [
        "all (default): All goals must be true",
        "one: Just one goal needs to be true",
        "half: Half of the goals must be true",
        "none: No goal must be true"
      ]
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/goals/playerattackedbyplayer.json
{
  "name": "PlayerAttackedByPlayer",
  "category": "<dummy>",
  "documentation": "Satisfied if the given player A has attacked the given player B. TODO Unclear what order",
  "parameters": [
    {
      "name": "PlayerIdA",
      "type": "NUMBER"
    },
    {
      "name": "PlayerIdB",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/results/enablejob.json
{
  "name": "EnableJob",
  "category": "<dummy>",
  "documentation": "Enables the given job that the given player was unable to assign because of missing experience.",
  "parameters": [
    {
      "name": "PlayerId",
      "type": "NUMBER"
    },
    {
      "name": "TribeType",
      "type": "NUMBER"
    },
    {
      "name": "JobType",
      "type": "TYPE"
    }
  ]
}
