=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/product.schema.json",
  "title": "CulturesIniParameterInformation",
  "description": "The definition of a parameter in the map.ini in Cultures.",
  "type": "object",
  "properties": {
    "name": {
      "description": "Name of the command",
      "type": "string"
    },
    "category": {
      "description": "The category enum the command belongs to.",
      "type": "string"
    },
    "displayName": {
      "description": "A more readable name to display (camel case)",
      "type": "string"
    },
    "documentation": {
      "description": "Documentation about the usage of the command (markdown).",
      "type": "string"
    },
    "parametersMin": {
      "type": "number",
      "description": "Minimum count of parameters."
    },
    "parametersMax": {
      "type": "number",
      "description": "Maximum count of parameters."
    },
    "parameters": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "documentation": {
              "type": "string",
              "description": "(markdown)"
            },
            "type": {
              "type": "string",
              "enum": [
                "NUMBER",
                "TYPE"
              ]
            }
          },
          "anyOf": [
            {
              "properties": {
                "type": {
                  "const": "NUMBER"
                },
                "numberRange": {
                  "type": "object",
                  "properties": {
                    "min": {
                      "type": "integer"
                    },
                    "max": {
                      "type": "integer"
                    }
                  },
                  "additionalProperties": false
                },
                "numberHint": {
                  "type": "array",
                  "description": "Assigns names to the numbers this parameter takes. Used for automatic documentation to show the user-friendly name for numbers. Array is zero-based. Special value `<NONE>` is hidden from the user.",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                },
                "numberHintsBitfield": {
                  "type": "array",
                  "description": "Like number hint, but assigns a user-friendly name to every bit of the number taken by this parameter. Array starts with the lowest-value bit.",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                }
              },
              "required": [
                "type"
              ],
              "additionalProperties": false
            },
            {
              "properties": {
                "type": {
                  "const": "TYPE"
                }
              }
            }
          ],
          "required": [
            "name",
            "type"
          ],
          "additionalProperties": false
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "name",
    "category",
    "parameters"
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/results/changemissionidofplayersvehiclesoncontinent.json
{
  "name": "ChangeMissionIdOfPlayersVehiclesOnContinent",
  "category": "<dummy>",
  "documentation": "Changes the id of all vehicles of the given player on the given continent.",
  "parameters": [
    {
      "name": "PlayerId",
      "type": "NUMBER"
    },
    {
      "name": "PosX",
      "type": "NUMBER"
    },
    {
      "name": "PosY",
      "type": "NUMBER"
    },
    {
      "name": "VehicleId",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/ai_setcondition_onexternal.json
{
  "name": "AI_SetCondition_OnExternal",
  "category": "aidata",
  "documentation": "Sets the given condition of the given player via mission result `SetExternalFlag` with given initial value.",
  "parameters": [
    {
      "name": "PlayerId",
      "type": "NUMBER"
    },
    {
      "name": "ConditionId",
      "type": "NUMBER"
    },
    {
      "name": "InitialValue",
      "type": "NUMBER",
      "numberRange": {
        "min": 0,
        "max": 1
      },
      "numberHints": [
        "false",
        "true"
      ]
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/results/setplayerbehaviourflag.json
{
  "name": "SetPlayerBehaviourFlag",
  "category": "<dummy>",
  "documentation": "Changes the behaviour flag of all humans of the given player.",
  "parameters": [
    {
      "name": "PlayerId",
      "type": "NUMBER"
    },
    {
      "name": "Behaviour",
      "type": "NUMBER",
      "numberHintsBitfield": [
        "DisableNeeds",
        "DisableJob",
        "DisableFight",
        "Immortal",
        "DisableMessages",
        "DisableControl",
        "DisableJobChange",
        "Important",
        "UserSectorMove",
        "SlowMovement",
        "DoNoChangePalette",
        "NoExperienceGain",
        "NoShoeToolDrain",
        "AnimalsIgnoreHuman",
        "Ghost",
        "DontCryForHelp",
        "DefendMode",
        "FastMovement",
        "NeverGrowUp",
        "ActsLikeAHero"
      ]
    },
    {
      "name": "IsEnabled",
      "type": "NUMBER",
      "numberRange": {
        "min": 0,
        "max": 1
      }
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/goals/findposbyhumans.json
{
  "name": "FindPosByHumans",
  "category": "<dummy>",
  "documentation": "Satisfied if the given human is inside the given area.",
  "parameters": [
    {
      "name": "HumanId",
      "type": "NUMBER"
    },
    {
      "name": "PosX",
      "type": "NUMBER"
    },
    {
      "name": "PosY",
      "type": "NUMBER"
    },
    {
      "name": "Radius",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/results/setvertexcoloronland.json
{
  "name": "SetVertexColorOnLand",
  "category": "<dummy>",
  "documentation": "Sets the given vertex color in the given area, but only on land.",
  "parameters": [
    {
      "name": "PosX",
      "type": "NUMBER"
    },
    {
      "name": "PosY",
      "type": "NUMBER"
    },
    {
      "name": "Radius",
      "type": "NUMBER"
    },
    {
      "name": "VertexColor",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/goals/chestnearpos.json
{
  "name": "ChestNearPos",
  "category": "<dummy>",
  "documentation": "Satisfied if there is a chest in the given area.\n\n*Note*: Only closed chests count as chests.",
  "parameters": [
    {
      "name": "PosX",
      "type": "NUMBER"
    },
    {
      "name": "PosY",
      "type": "NUMBER"
    },
    {
      "name": "Radius",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/ai_setcondition_onconditions.json
{
  "name": "AI_SetCondition_OnConditions",
  "category": "aidata",
  "documentation": "Sets the given condition of the given player based on the given operation and on given other conditions. E.g. `and`, `or`, ...",
  "parametersMin": 1,
  "parametersMax": -1,
  "parameters": [
    {
      "name": "PlayerId",
      "type": "NUMBER"
    },
    {
      "name": "ConditionId",
      "type": "NUMBER"
    },
    {
      "name": "EverActive",
      "type": "NUMBER",
      "numberRange": {
        "min": 0,
        "max": 1
      },
      "numberHints": [
        "Stay true if became true.",
        "Resets the condition back to false when read."
      ]
    },
    {
      "name": "LogicalOperation",
      "type": "NUMBER",
      "documentation": "The logical operation that is applied to the state of all condition to determine the value of this condition.",
      "numberHints": [
        "AND",
        "OR",
        "none",
        "exactly one"
      ]
    },
    {
      "name": "OtherConditionId1",
      "type": "NUMBER"
    },
    {
      "name": "OtherConditionId2",
      "type": "NUMBER"
    },
    {
      "name": "OtherConditionId3",
      "type": "NUMBER"
    },
    {
      "name": "OtherConditionId4",
      "type": "NUMBER"
    },
    {
      "name": "OtherConditionId5",
      "type": "NUMBER"
    },
    {
      "name": "OtherConditionId6",
      "type": "NUMBER"
    },
    {
      "name": "OtherConditionIdN",
      "type": "NUMBER"
    }
  ]
}

=== Nithanim/cultures-map-development-kit/server/src/main/resources/me/nithanim/cultures/lsp/processor/lines/commands/goals/goodproduceable.json
{
  "name": "GoodProduceable",
  "category": "<dummy>",
  "documentation": "Satisfied if a given player has unlocked a given good (regardless of the source).",
  "parameters": [
    {
      "name": "PlayerId",
      "type": "NUMBER"
    },
    {
      "name": "TribeType",
      "type": "TYPE"
    },
    {
      "name": "GoodType",
      "type": "TYPE"
    }
  ]
}
